version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lastest
    steps:
      - checkout
      - run: echo "npm install"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "TESTING"
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:lastest
    steps:
      - checkout
      - run: echo "HELLLOOO"
workflows:
  version: 2
  build_test_and_list:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
