version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Helllooo"
  sally:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Double trouble"
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally
